# List Comprehension

In [3]:
result = [];

for i in range(10):
    result.append(i)

print(result);
print();

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]



In [4]:
result2 = [i for i in range(10)];
print(result2);

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
result = [];

for i in range(10):
    if i % 2 == 0:
        result.append(i);

print(result);
print();

[0, 2, 4, 6, 8]



In [7]:
result2 = [i for i in range(10) if i % 2 == 0];
print(result2);

[0, 2, 4, 6, 8]


In [10]:
result = [];

for i in range(10):
    if i % 2 == 0:
        result.append(i);
    else:
        result.append(99);

print(result);
print();

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]



In [11]:
result2 = [i if i % 2 == 0 else 99 for i in range(10)];
print(result2);

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]


In [15]:
result = [];
case1 = ['A', 'B', 'C'];
case2 = ['A', 'B', 'C'];
for i in case1:
    for j in case2:
        result.append(i + j);
        
print(result);

['AB', 'AC', 'BA', 'BC', 'CA', 'CB']


In [14]:
result2 = [i + j for i in case1 for j in case2];
print(result2);

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


In [16]:
result2 = [i + j for i in case1 for j in case2 if i != j];
print(result2);

['AB', 'AC', 'BA', 'BC', 'CA', 'CB']


# numpy (파이썬 배열의 단점을 보완. ML을 하려면 필수!!)

In [17]:
import numpy as np

In [18]:
a1 = np.array([0, 1, 2, 3, 4, 5]);
print(a1);

[0 1 2 3 4 5]


In [19]:
print(type(a1));

<class 'numpy.ndarray'>


In [20]:
print(a1.dtype);

int32


In [21]:
list1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]];
print(list1);

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [23]:
list2 = np.array(list1);
print(list2);

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a = np.arange(0, 10, 2);
print(a);

[0 2 4 6 8]


In [26]:
a = np.arange(10);
print(a);

[0 1 2 3 4 5 6 7 8 9]


In [27]:
a = np.arange(1, 10);
print(a);

[1 2 3 4 5 6 7 8 9]


In [29]:
a = np.arange(12).reshape(4, 3);
print(a);

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
a = np.arange(12).reshape(4, -1);
print(a);

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [32]:
a = np.arange(12).reshape(-1, 3);
print(a);

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
a = np.linspace(1, 10, 10);
print(a);

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [39]:
a = np.linspace(1, 10, 8);
print(a);

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [42]:
a1 = np.zeros(10, int);
print(a1);

a2 = np.zeros((3, 4), int);
print(a2);

a3 = np.ones(5);
print(a3);

a4 = np.ones((3, 5));
print(a4);

a5 = np.eye(3);
print(a5);

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
list1 = [10, 20, 30, 40];
list2 = [1, 2, 3, 4];
print(list1 + list2);

[10, 20, 30, 40, 1, 2, 3, 4]


In [56]:
a1 = np.array(list1);
a2 = np.array(list2);
print(a1 + a2);

[11 22 33 44]


In [57]:
print(a1 > a2);

[ True  True  True  True]


In [7]:
import numpy as np

a1 = np.arange(1, 6);

print(a1.sum());
print(a1.mean());
print(a1.std());
print(a1.var());
print(a1.min());
print(a1.max());
print(a1.cumsum()); # 누적합
print(a1.cumprod());

15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [11]:
a = np.array([0, 1, 2, 3]).reshape(2, 2);
print(a);

b = np.array([3, 2, 0, 1]).reshape(2, 2);
print(b);

print('-'*20);
print(a.dot(b)); # 행렬곲
print(np.dot(a, b)); # 행렬곲

print('-'*20);
print(np.transpose(a)); # 전치행렬
print(a.transpose()); # 전치행렬
print(a.T); # 전치행렬

print('-'*20);
print(np.linalg.inv(a)); # 역행렬
print(np.linalg.det(a)); # 행렬식

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]
--------------------
[[0 1]
 [6 7]]
[[0 1]
 [6 7]]
--------------------
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
--------------------
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


In [15]:
a = np.array([0, 10, 20, 30, 40, 50]);
print(a[[1, 3, 4]]);

b = np.arange(10, 100, 10).reshape(3, 3);
print('-'*20);
print(b);
print('-'*20);

print(b[0, 2]);
b[2, 2] = 97;
print(b);
print(b[1]);

print('-'*20);
b[1] = np.array([45, 55, 65]);
print(b);
b[2] = [75, 85, 95];
print(b);

print('-'*20);
print(b[[0, 2], [0, 1]]);

[10 30 40]
--------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
--------------------
30
[[10 20 30]
 [40 50 60]
 [70 80 97]]
[40 50 60]
--------------------
[[10 20 30]
 [45 55 65]
 [70 80 97]]
[[10 20 30]
 [45 55 65]
 [75 85 95]]
--------------------
[10 85]


In [17]:
a = np.array([1, 2, 3, 4, 5, 6]);

print(a[a > 3]);
print(a[(a % 2) == 0]);

[4 5 6]
[2 4 6]


In [19]:
a = np.array([0, 10, 20, 30, 40, 50]);

print(a[1:4]);
print(a[:3]);
print(a[2:]);
a[2:5] = np.array([25, 35, 45]);
print(a);

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [21]:
a = np.arange(10, 100, 10).reshape(3, 3);

print('-'*20);
print(a);
print('-'*20);

print(a[1:3, 1:3]);
print(a[:3, 1:]);
print(a[1][0:2]);
a[0:2, 1:3] = np.array([[25, 35], [55, 65]]);
print(a);

--------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
--------------------
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[[10 25 35]
 [40 55 65]
 [70 80 90]]
